name: Testing on ubuntu-latest

on:
  push:
  pull_request:
  schedule:
    - cron: '0 12 * * 0'

env:
  SKBUILD_BUILD_OPTIONS: --verbose

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Set up requirements & configuration variables
        run: |
          brew update
          brew install cmake
          pip install --upgrade pip wheel
          pip install -r test_requirements.txt
          echo "CASM_PREFIX=$(python -m libcasm.casmglobal --prefix)" >> "$GITHUB_ENV"
          CASM_SOFLAGS="-shared -Wl,--no-as-needed"
          echo "CASM_SOFLAGS=${CASM_SOFLAGS}" >> "$GITHUB_ENV"

      - name: make
        shell: bash
        run: |
          pip install .

      - name: make test
        shell: bash
        run: |
          python -m pytest -rsap tests

      - name: Set up doc requirements
        run: |
          pip install -r doc_requirements.txt

      - name: build docs
        shell: bash
        run: |
          cd python/doc
          sphinx-build -b html . _build/html

      - name: upload docs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: libcasm-configuration-docs
          path: python/doc/_build/html
