name: Testing on macos-latest

on:
  push:
  pull_request:
  schedule:
    - cron: '0 12 * * 0'

jobs:
  build:
    runs-on: macOS-latest
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install build requirements
        run: |
          brew update
          brew install cmake
          pip install --upgrade -r build_requirements.txt

      - name: make
        shell: bash
        run: |
          pip install .

      - name: Install test requirements & set configuration variables
        run: |
          pip install -r test_requirements.txt
          echo "CASM_PREFIX=$(python -m libcasm.casmglobal --prefix)" >> "$GITHUB_ENV"

      - name: make test
        shell: bash
        run: |
          python -m pytest -rsap tests
