name: Testing on ubuntu-latest

on:
  push:
  pull_request:
  schedule:
    - cron: '0 12 * * 0'

env:
  SKBUILD_BUILD_OPTIONS: --verbose

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install build requirements
        run: |
          sudo apt-get update
          sudo apt-get install build-essential cmake
          pip install --upgrade -r build_requirements.txt

      - name: make
        shell: bash
        run: |
          pip install .

      - name: Install test requirements & set configuration variables
        run: |
          pip install -r test_requirements.txt
          echo "CASM_PREFIX=$(python -m libcasm.casmglobal --prefix)" >> "$GITHUB_ENV"
          CASM_SOFLAGS="-shared -Wl,--no-as-needed"
          echo "CASM_SOFLAGS=${CASM_SOFLAGS}" >> "$GITHUB_ENV"

      - name: make test
        shell: bash
        run: |
          python -m pytest -rsap tests
